/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AboutContent = IDL.Record({
  'about' : IDL.Text,
  'mission' : IDL.Text,
  'values' : IDL.Text,
  'vision' : IDL.Text,
});
export const Event = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'location' : IDL.Text,
});
export const InquiryType = IDL.Variant({
  'donation' : IDL.Null,
  'collaboration' : IDL.Null,
  'membership' : IDL.Null,
  'general' : IDL.Null,
});
export const Time = IDL.Int;
export const Inquiry = IDL.Record({
  'inquiryType' : InquiryType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'organization' : IDL.Text,
});

export const idlService = IDL.Service({
  'addEvent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAboutContent' : IDL.Func([], [AboutContent], ['query']),
  'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'initializeContent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, InquiryType],
      [Inquiry],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AboutContent = IDL.Record({
    'about' : IDL.Text,
    'mission' : IDL.Text,
    'values' : IDL.Text,
    'vision' : IDL.Text,
  });
  const Event = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'location' : IDL.Text,
  });
  const InquiryType = IDL.Variant({
    'donation' : IDL.Null,
    'collaboration' : IDL.Null,
    'membership' : IDL.Null,
    'general' : IDL.Null,
  });
  const Time = IDL.Int;
  const Inquiry = IDL.Record({
    'inquiryType' : InquiryType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'organization' : IDL.Text,
  });
  
  return IDL.Service({
    'addEvent' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAboutContent' : IDL.Func([], [AboutContent], ['query']),
    'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'initializeContent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, InquiryType],
        [Inquiry],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };