/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutContent {
  'about' : string,
  'mission' : string,
  'values' : string,
  'vision' : string,
}
export interface Event {
  'title' : string,
  'date' : string,
  'description' : string,
  'location' : string,
}
export interface Inquiry {
  'inquiryType' : InquiryType,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'organization' : string,
}
export type InquiryType = { 'donation' : null } |
  { 'collaboration' : null } |
  { 'membership' : null } |
  { 'general' : null };
export type Time = bigint;
export interface _SERVICE {
  'addEvent' : ActorMethod<[string, string, string, string], undefined>,
  'getAboutContent' : ActorMethod<[], AboutContent>,
  'getEvents' : ActorMethod<[], Array<Event>>,
  'getInquiries' : ActorMethod<[], Array<Inquiry>>,
  'initializeContent' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'submitInquiry' : ActorMethod<
    [string, string, string, string, InquiryType],
    Inquiry
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];